* Encoding: UTF-8.
IF( year<18)  MAYOREDAD=1.
IF( year>=18)  MAYOREDAD=2.
EXECUTE

FREQUENCIES VARIABLES=   MAYOREDAD
  /BARCHART FREQ    
  /ORDER=ANALYSIS.

FREQUENCIES VARIABLES= MAYOREDAD
  /PIECHART PERCENT        
  /ORDER=ANALYSIS    



